# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Buah', models.CharField(max_length=50)),
                ('Warna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'buah_fruit',
            },
        ),
    ]
