# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='Warna',
        ),
        migrations.AddField(
            model_name='fruit',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='Nama_Buah',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
