# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buah', '0002_auto_20180521_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='Tipe',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
