# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buah', '0007_auto_20180521_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='Tipe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
